version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    container_name: project-backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    container_name: project-frontend
    depends_on:
      - backend
    restart: unless-stopped
    links:
      - backend
